<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\DataAcquisition.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\ttech.png" />
    <None Remove="Assets\ttech2.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\DataAcquisition.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\ttech.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\ttech2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentModbus" Version="5.0.3" />
    <PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="7.0.10" />
    <PackageReference Include="System.IO.Ports" Version="7.0.0" />
  </ItemGroup>

</Project>
